Repository ArkEcosystem/paper-wallet, pull requests merged in 2019-07, with the labels that each got.

#18 chore(deps): update all dependencies to their latest versions
  .babelrc
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  gulpfile.babel.js
  lib/index.css
  lib/index.js
  lib/wallet.js
  package.json
  src/wallet.js
  yarn.lock
Labels: Complexity: Undetermined, Type: Task

#20 chore(readme): add lead maintainer information
  README.md
Labels: Complexity: Low, Type: Task

#21 fix: update helper scripts
  scripts/deploy.sh
  scripts/release.sh
Labels: Complexity: Low, Type: Bugfix

#23 refactor: remove wallet data from URL
  src/router.ts
Labels: Complexity: Low, Type: Refactor

#22 fix: wallet image saving on iOS
  CHANGELOG.md
  src/views/Wallet.vue
Labels: Complexity: Low
